<?php

namespace Http\Client\Plugin\Vcr;

use PHPUnit_Framework_Test;

class VcrTestListener extends \PHPUnit_Framework_BaseTestListener
{
    public function startTest(PHPUnit_Framework_Test $test)
    {
        parent::startTest($test); // TODO: Change the autogenerated stub
    }

    public function endTest(PHPUnit_Framework_Test $test, $time)
    {
        parent::endTest($test, $time); // TODO: Change the autogenerated stub
    }
}
